code --install-extension andys8.jest-snippets
code --install-extension be5invis.vscode-custom-css
code --install-extension christian-kohler.path-intellisense
code --install-extension craigthomas.supersharp
code --install-extension dbaeumer.vscode-eslint
code --install-extension doggy8088.netcore-snippets
code --install-extension eamodio.gitlens
code --install-extension EditorConfig.EditorConfig
code --install-extension esbenp.prettier-vscode
code --install-extension formulahendry.dotnet-test-explorer
code --install-extension Gruntfuggly.todo-tree
code --install-extension jalisimo.react-jest-vscode-snippets
code --install-extension jchannon.csharpextensions
code --install-extension jorgeserrano.vscode-csharp-snippets
code --install-extension josephwoodward.vscodeilviewer
code --install-extension jpoissonnier.vscode-styled-components
code --install-extension k--kato.docomment
code --install-extension KishoreIthadi.dotnet-core-essentials
code --install-extension ms-azuretools.vscode-docker
code --install-extension ms-vscode.csharp
code --install-extension msjsdiag.debugger-for-chrome
code --install-extension oderwat.indent-rainbow
code --install-extension pflannery.vscode-versionlens
code --install-extension Prisma.vscode-graphql
code --install-extension quicktype.quicktype
code --install-extension RobbOwen.synthwave-vscode
code --install-extension salbert.awesome-dotnetcore-pack
code --install-extension salbert.copy-text
code --install-extension tht13.html-preview-vscode
code --install-extension tintoy.msbuild-project-tools
code --install-extension vincaslt.highlight-matching-tag
code --install-extension vortizhe.simple-ruby-erb
code --install-extension WakaTime.vscode-wakatime